class HardwareSettings:
    
    CAM_NUM = 1

    BUZZER_PIN = 12

    FAN_PIN = 13

    FLOW_SENSOR_OVAL_GEAR_PIN = 23
    FLOW_SENSOR_PADDLE_BRASS_PIN = 17
    FLOW_SENSOR_PADDLE_PLASTIC_PIN = 23

    TEMP_SENSOR_I2C_BUS = 1
    LIGHT_SENSOR_I2C_BUS = 1

    LPR_IP_ADDRESS = "192.168.1.100"

    RADAR_UART_TTY = "/dev/ttyS0"
    RADAR_UART_BAUDRATE = 115200

    GPS_UART_TTY = "/dev/ttyS0"
    GPS_UART_BAUDRATE = 9500

    INCLIOMETER_MODEL = "HCA"
    INCLIOMETER_UART_TTY = "/dev/ttyS0"
    INCLIOMETER_UART_BAUDRATE = 9500

    MOTOR_CONTROLLER_ADDRESS = 128
    MOTOR_CONTROLLER_UART_TTY = "/dev/ttyS0"
    MOTOR_CONTROLLER_UART_BAUDRATE = 9500

    IO_EXPANDER_SPI_BUS = 0
    IO_EXPANDER_SPI_DEVICE = 0
    IO_EXPANDER_SPI_BUS_SPEED = 500000

    ADC_I2C_BUS = 1

    ADC_SPI_BUS = 0
    ADC_SPI_DEVICE = 1
    ADC_SPI_BUS_SPEED = 500000
